/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperature;

import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author Chris
 */
public class TemperatureFrame extends javax.swing.JFrame {
    String store;
    /**
     * Creates new form TemperatureFrame
     */
    public TemperatureFrame() {
        initComponents();
        store = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        celcRad = new javax.swing.JRadioButton();
        farenRad = new javax.swing.JRadioButton();
        kelvRad = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        convertButton = new javax.swing.JButton();
        prompt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Javanese Text", 2, 14)); // NOI18N
        jLabel1.setText("Tempertaure Converter 0.1 Alpha");

        jLabel2.setText("Enter Temperature");

        buttonGroup1.add(celcRad);
        celcRad.setSelected(true);
        celcRad.setLabel("Celcius");
        celcRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celcRadActionPerformed(evt);
            }
        });

        buttonGroup1.add(farenRad);
        farenRad.setLabel("Farenheit");
        farenRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farenRadActionPerformed(evt);
            }
        });

        buttonGroup1.add(kelvRad);
        kelvRad.setLabel("Kelvin");
        kelvRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelvRadActionPerformed(evt);
            }
        });

        jScrollPane2.setFocusable(false);

        result.setEditable(false);
        result.setColumns(20);
        result.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        result.setRows(5);
        jScrollPane2.setViewportView(result);

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        prompt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        prompt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promptActionPerformed(evt);
            }
        });
        prompt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                promptKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convertButton)
                            .addComponent(prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(farenRad)
                            .addComponent(celcRad)
                            .addComponent(kelvRad))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celcRad)
                    .addComponent(prompt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(farenRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kelvRad))
                    .addComponent(convertButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void celcRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celcRadActionPerformed
        if(!result.getText().equals("") && store.equals(prompt.getText()))
            convert();
    }//GEN-LAST:event_celcRadActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
       convert();
    }//GEN-LAST:event_convertButtonActionPerformed

    private void farenRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farenRadActionPerformed
        if(!result.getText().equals("") && store.equals(prompt.getText()))
            convert();
    }//GEN-LAST:event_farenRadActionPerformed

    private void kelvRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelvRadActionPerformed
        if(!result.getText().equals("") && store.equals(prompt.getText()))
            convert();
    }//GEN-LAST:event_kelvRadActionPerformed

    private void promptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promptActionPerformed

    private void promptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_promptKeyPressed
      if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
          convert();
      }
          
    }//GEN-LAST:event_promptKeyPressed
    private void convert()
    {
        store = prompt.getText();
        double temp = 0;
       if(!prompt.getText().equals(""))    
        temp = Double.parseDouble(prompt.getText());
       double celcValue = 0,farenValue= 0,kelvValue= 0;
       if(celcRad.isSelected())
       {
           celcValue = temp;
           farenValue = temp * (9/5d) + 32;
           kelvValue = celcValue + 273.15d;
       }
       if(farenRad.isSelected())
       {
           celcValue = temp * (5d/9) - 32;
           farenValue = temp;
           kelvValue = celcValue + 273.15d;
       }
       if(kelvRad.isSelected())
       {
           celcValue = temp - 273.15d;
           farenValue = celcValue * (9/5d) + 32;
           kelvValue = temp;
       }
       result.setText(new BigDecimal(celcValue).setScale(3,RoundingMode.DOWN) + " degrees Celcius\n\n" + new BigDecimal(farenValue).setScale(3,RoundingMode.DOWN) + " degrees Farenheit\n\n" + new BigDecimal(kelvValue).setScale(3,RoundingMode.DOWN) + " Kelvin");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton celcRad;
    private javax.swing.JButton convertButton;
    private javax.swing.JRadioButton farenRad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton kelvRad;
    private javax.swing.JFormattedTextField prompt;
    private javax.swing.JTextArea result;
    // End of variables declaration//GEN-END:variables
}
